// <auto-generated />
using API_Service.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace API_Service.Migrations
{
    [DbContext(typeof(SmartHomeDbContext))]
    [Migration("20210425212708_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("API_Service.Models.Device", b =>
                {
                    b.Property<int>("serial_number")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("DeviceTypename")
                        .HasColumnType("text");

                    b.Property<string>("brand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("electric_usage")
                        .HasColumnType("integer");

                    b.HasKey("serial_number");

                    b.HasIndex("DeviceTypename");

                    b.ToTable("devices");
                });

            modelBuilder.Entity("API_Service.Models.DeviceType", b =>
                {
                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("warranty_months")
                        .HasColumnType("integer");

                    b.HasKey("name");

                    b.ToTable("device_types");
                });

            modelBuilder.Entity("API_Service.Models.Distributor", b =>
                {
                    b.Property<int>("legal_card")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("continent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("legal_card");

                    b.ToTable("distributors");
                });

            modelBuilder.Entity("DeviceDistributor", b =>
                {
                    b.Property<int>("devicesserial_number")
                        .HasColumnType("integer");

                    b.Property<int>("distributorslegal_card")
                        .HasColumnType("integer");

                    b.HasKey("devicesserial_number", "distributorslegal_card");

                    b.HasIndex("distributorslegal_card");

                    b.ToTable("DeviceDistributor");
                });

            modelBuilder.Entity("API_Service.Models.Device", b =>
                {
                    b.HasOne("API_Service.Models.DeviceType", null)
                        .WithMany("devices")
                        .HasForeignKey("DeviceTypename");
                });

            modelBuilder.Entity("DeviceDistributor", b =>
                {
                    b.HasOne("API_Service.Models.Device", null)
                        .WithMany()
                        .HasForeignKey("devicesserial_number")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_Service.Models.Distributor", null)
                        .WithMany()
                        .HasForeignKey("distributorslegal_card")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("API_Service.Models.DeviceType", b =>
                {
                    b.Navigation("devices");
                });
#pragma warning restore 612, 618
        }
    }
}
