CREATE TABLE devices(
	serial_number		DECIMAL(10)	NOT NULL,
	device_type_name	VARCHAR(30) NOT NULL,
	brand				VARCHAR(15)	NOT NULL,
	electric_usage		DECIMAL(10)	NOT NULL,
	PRIMARY KEY(serial_number)
);

CREATE TABLE device_types(
	name			VARCHAR(30)	NOT NULL,
	description		VARCHAR(100) NOT NULL,
	warranty_months	DECIMAL(2)	NOT NULL,
	PRIMARY KEY(name)
);

CREATE TABLE distributors(
	legal_card		DECIMAL(10)	NOT NULL,
	name			VARCHAR(30) NOT NULL,
	country			VARCHAR(30)	NOT NULL,
	continent		VARCHAR(30)	NOT NULL,
	PRIMARY KEY(legal_card)
);

CREATE TABLE device_distributor
(
    devices_serial_number 	DECIMAL(10) NOT NULL,
    distributors_legal_card DECIMAL(10) NOT NULL,
    PRIMARY KEY (devices_serial_number, distributors_legal_card)
)

CREATE TABLE orders
(
    consecutive 	INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    bill_number 	INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    price 			INTEGER NOT NULL,
    purchase_date 	DATE NOT NULL,
    purchase_time 	CHAR(5) NOT NULL,
    device_number 	DECIMAL(10),
	client_email 	VARCHAR(30) NOT NULL,
    PRIMARY KEY (consecutive, bill_number)    
)

CREATE TABLE clients
(
    email 		VARCHAR(30) NOT NULL,
    name 		VARCHAR(30) NOT NULL,
    password 	VARCHAR(30) NOT NULL,
    last_name1 	VARCHAR(30) NOT NULL,
    last_name2 	VARCHAR(30) NOT NULL,
    country 	VARCHAR(30) NOT NULL,
    continent 	VARCHAR(30) NOT NULL,
    PRIMARY KEY (email)
)

CREATE TABLE chambers
(
    name 			VARCHAR(30) NOT NULL,
    client_email 	VARCHAR(30) NOT NULL,
    PRIMARY KEY (name)
)

ALTER TABLE devices
ADD CONSTRAINT DEVICES_DEVICE_TYPES_FK FOREIGN KEY (device_type_name)
REFERENCES device_types (name);

ALTER TABLE device_distributor
ADD CONSTRAINT DEVICE_DISTRIBUTOR_SERIAL_NUMBER_FK FOREIGN KEY (devices_serial_number)
REFERENCES devices (serial_number);

ALTER TABLE device_distributor
ADD CONSTRAINT DEVICE_DISTRIBUTOR_LEGAL_CARD_FK FOREIGN KEY (distributors_legal_card)
REFERENCES distributors (legal_card);

ALTER TABLE orders
ADD CONSTRAINT ORDERS_DECIVES_DEVICE_NUMBER_FK FOREIGN KEY (device_number)
REFERENCES devices (serial_number);

ALTER TABLE orders
ADD CONSTRAINT ORDERS_CLIENTS_EMAIL_FK FOREIGN KEY (client_email)
REFERENCES clients (email);

ALTER TABLE chambers
ADD CONSTRAINT CHAMBERS_CLIENTS_FK FOREIGN KEY (client_email)
REFERENCES clients (email);

INSERT INTO device_types(name, description, warranty_months)
VALUES ('Refrigeradoras', 'Refris inteligentes', 24)


